version: "3.1"
services:
  mariadb:
    image: "mariadb:11.0"
    container_name: payment_api_mariadb
    working_dir: /application
    volumes:
      - ".:/application"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_USER}
      - MYSQL_DATABASE=${MARIADB_DB_NAME}
      - MYSQL_USER=${MARIADB_DB_USER}
      - MYSQL_PASSWORD=${MARIADB_DB_USER_PASSWORD}
    ports:
      - "26003:3306"

  webserver:
    image: "nginx:alpine"
    container_name: payment_api_webserver
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "26000:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: payment_api_php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /application
    expose:
      - 9000
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"
      - "./phpdocker/php-fpm/error_reporting.ini:/etc/php/8.2/fpm/conf.d/error_reporting.ini"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    container_name: payment_api_phpmyadmin
    ports:
      - "26001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=payment_api_mariadb

  composer:
    image: "composer:latest"
    container_name: payment_api_composer
    command: ["composer", "update"]
    volumes:
      - ".:/app"
